version: "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules/:/etc/prometheus/alert_rules/
    ports:
      - 9090:9090

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
